apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
     containers:
      - name: webapp
        image: spothound/web_app
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: webapp
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32121
  selector:
    app: webapp
