---
- hosts: localhost
  name: Create AWS infrastructure with Terraforms
  vars:
    terraform_dir: ../terraform

  tasks:
    - name: Create AWS instances with Terraform
      terraform:
        project_path: "{{ terraform_dir }}"
        state: present
      register: outputs

    - name: Add all instance public DNS to host group
      add_host:
        name: "{{ item }}"
        groups: ec2instances
      loop: "{{ outputs.outputs.address.value }}"

- hosts: ec2instances
  name: Provision ec2 instance
  user: ec2-user
  become: yes
  gather_facts: false

  tasks:
    - name: Wait for instances to become reachable over SSH
      wait_for_connection:
        delay: 3
        timeout: 60

    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - amazon-linux-extras
        - git

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install docker-ce (centos) via amazon-linux-extras packages
      shell: "amazon-linux-extras install docker=18.06.1 -y"

    - name: Enable Docker CE service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure Python pip packages are installed
      pip:
        name: "{{ packages }}"
      vars:
        packages:
        - docker-py

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/spothound/simple_web.git'
        dest: /home/ec2-user/simple_web

    - name: build container image
      docker_image:
        name: simple_web
        build:
          path: /home/ec2-user/simple_web
        source: build
        state: present

    - name: Start service docker
      docker_container:
        name: simple_web
        image: simple_web
        state: present
        exposed_ports:
          - 80
        published_ports:
          - 80:80